---
title: "Peer Assessment 02"
author: "Luis Urbina"
date: "Tuesday, May 19, 2015"
output: html_document
---

#### Assignment
* Goal: explore the NOAA Storm Database and answer questions about severe weather events.
* Use the database 
* Answer the questions below 
* Show the code for your entire analysis
* Analysis consist of tables, figures, or other summaries
* Use any R package you want to support your analysis.
* Write your report as if it were to be read by a government or municipal manager who might be responsible for preparing for severe weather events and will need to prioritize resources for different types of events. However, there is no need to make any specific recommendations in your report.

#### Questions
* Across the United States, which types of events (as indicated in the `EVTYPE` variable) are most harmful with respect to population health?
* Across the United States, which types of events have the greatest economic consequences?

#### Requirements
* Use: RStudio, knitr, RPubs

#### Document Layout
* Title: it briefly summarizes your data analysis.
* Synopsis: it describes and summarizes your analysis in 10 complete sentences.
* Data Processing: it describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the `cache = TRUE` option for certain code chunks.
* Results: it is presented your results.
* Other sections may be included.
* The analysis document must have at least one figure containing a plot.
* Your analyis must have no more than three figures (i.e. panel plots or multiple plots).
* Show all your code: `echo = TRUE` for every code chunk (default setting in knitr).

#### Publishing Your Analysis
* Publish your analysis on RPubs.com. 
* NOTE: If you are having trouble connecting with RPubs due to proxy-related or other issues, you can upload your final analysis document file as a PDF to Coursera instead.
